{{- if not .Values.existingLogsConfigMapName }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "node.fullname" . }}-logs-config
  labels:
    {{- include "node.labels" . | nindent 4 }}
data:
  logs.config.yml: |
    {{- if .Values.logsConfig }}
    {{- .Values.logsConfig | nindent 4 }}
    {{- else }}
    {{- .Files.Get "files/logs.config.yml" | nindent 4 }}
    {{- end }}
{{- end }}
