{{- if and .Values.basestate (not .Values.existingBasestateConfigMapName) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "node.fullname" . }}-basestate
  labels:
    {{- include "node.labels" . | nindent 4 }}
binaryData:
  basestate.boc: {{ .Values.basestate }}
{{- end }}
