{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "node.fullname" . }}
  labels:
    {{- include "node.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "node.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: {{ .Values.ports.adnl }}
          protocol: UDP
      from:
        {{- if .Values.networkPolicy.adnl.allowFrom }}
        {{- toYaml .Values.networkPolicy.adnl.allowFrom | nindent 8 }}
        {{- else }}
        - ipBlock:
            cidr: 0.0.0.0/0
        {{- end }}
    {{- if and .Values.ports.control .Values.networkPolicy.control.enabled }}
    - ports:
        - port: {{ .Values.ports.control }}
          protocol: TCP
      {{- with .Values.networkPolicy.control.allowFrom }}
      from:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if and .Values.ports.liteserver .Values.networkPolicy.liteserver.enabled }}
    - ports:
        - port: {{ .Values.ports.liteserver }}
          protocol: TCP
      {{- with .Values.networkPolicy.liteserver.allowFrom }}
      from:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if and .Values.ports.jsonRpc .Values.networkPolicy.jsonRpc.enabled }}
    - ports:
        - port: {{ .Values.ports.jsonRpc }}
          protocol: TCP
      {{- with .Values.networkPolicy.jsonRpc.allowFrom }}
      from:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if and .Values.ports.metrics .Values.networkPolicy.metrics.enabled }}
    - ports:
        - port: {{ .Values.ports.metrics }}
          protocol: TCP
      {{- with .Values.networkPolicy.metrics.allowFrom }}
      from:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- with .Values.networkPolicy.extraIngress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
