{{- if and .Values.nodeConfigs (not .Values.existingNodeConfigsSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ton-rust-node.fullname" . }}-node-configs
  labels:
    {{- include "ton-rust-node.labels" . | nindent 4 }}
stringData:
  {{- range $key, $value := .Values.nodeConfigs }}
  {{ $key }}: |
    {{- $value | nindent 4 }}
  {{- end }}
{{- end }}
