{{- if .Values.ports.metrics }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "node.fullname" . }}-metrics
  labels:
    {{- include "node.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  {{- if .Values.metrics.annotations.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.ports.metrics | quote }}
    prometheus.io/path: "/metrics"
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "node.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.ports.metrics }}
      protocol: TCP
{{- end }}
