{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nodectl.fullname" . }}
  labels:
    {{- include "nodectl.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "nodectl.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: {{ .Values.port }}
          protocol: TCP
      {{- if .Values.networkPolicy.allowCIDRs }}
      from:
        {{- range .Values.networkPolicy.allowCIDRs }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
      {{- end }}
    {{- with .Values.networkPolicy.extraIngress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
